apiVersion: v2
name: watchman
description: A Discord bot for news reporting and server monitoring with external API capabilities
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - discord
  - bot
  - monitoring
  - news
  - hacker-news
  - api
home: https://github.com/Trillius/watchman
icon: https://raw.githubusercontent.com/Trillius/watchman/main/assets/icon.png
sources:
  - https://github.com/Trillius/watchman
maintainers:
  - name: Trillius
    url: https://github.com/Trillius
annotations:
  category: Monitoring
