version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-news-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./logs:/app/logs
      - ./bot_data.db:/app/bot_data.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - API_HOST=0.0.0.0
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
