apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchman
  namespace: watchman
  labels:
    app: watchman
    component: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchman
      component: bot
  template:
    metadata:
      labels:
        app: watchman
        component: bot
    spec:
      serviceAccountName: watchman
      securityContext:
        fsGroup: 1000
      containers:
      - name: watchman
        image: watchman-discord-bot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8080"
        - name: DATABASE_URL
          value: "sqlite:///./data/bot_data.db"
        - name: NEWS_RSS_FEEDS
          value: "https://hnrss.org/frontpage"
        - name: NEWS_CHECK_INTERVAL
          value: "3600"
        - name: MONITOR_INTERVAL
          value: "300"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FILE
          value: "logs/bot.log"
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: watchman-secrets
              key: discord-token
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: watchman-secrets
              key: api-secret-key
        - name: DISCORD_GUILD_ID
          valueFrom:
            secretKeyRef:
              name: watchman-secrets
              key: discord-guild-id
              optional: true
        - name: NEWS_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: watchman-secrets
              key: news-channel-id
              optional: true
        - name: STATUS_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: watchman-secrets
              key: status-channel-id
              optional: true
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: watchman-data
      - name: logs
        persistentVolumeClaim:
          claimName: watchman-logs
